#!/usr/bin/env php
<?php

$autoloadFiles = [
	__DIR__ . "/../../autoload.php",
	__DIR__ . "/../vendor/autoload.php",
	__DIR__ . "/vendor/autoload.php"
];

$autoload = null;

foreach ($autoloadFiles as $autoloadFile) {
    if (file_exists($autoloadFile)) {
		$autoload = $autoloadFile;
        break;
    }
}

if (is_null($autoload)) {
	echo 
	"=======================\n".
	"= Unable to autoload! =\n".
	"=======================\n";
	return;
}

include_once $autoload;

return (new \intrawarez\slimannotations\cli\SlamConsole())->run();
